# This file is a template for all of the statistical data to be kept for the game.
# The game code will load this file along with a game_data.yaml file.  
# Any items not present in the game_data.yaml file will default to the 
# value specified here.  When game ends or when defaults are restored, 
# game_data will be written and will then contain every item here.

Audits:
  Games Played: 0
  Games Started: 0
  Machine Startups: 0
ClassicHighScoreData:
- {date: 'Sun Oct  3 17:38:46 2010', inits: ---, score: 80}
LastGameScores:
  LastPlayer1Score: 123
  LastPlayer2Score: 456
GrandChamp:
  GrandChampScore: 80
  GrandChampInits: ---