# P3-ROC Game Description file for Lucky 7 Prototype
PRGame:
    machineType: pdb
    numBalls: 4
PRFlippers:
    - nudgeLeft
    - nudgeRight
PRBumpers:
    - slingR
    - slingL
    - popBumper
    - coreRightSling
    - coreLeftSling
    - coreTopSling
PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #   tags: <group>
    #
    #   <number> can be: SDx or Raw Input#
    #   Bank A switch: P3-ROC switch # = SW-16 address * 16 + Bank A switch input #
    #   Bank B switch: P3-ROC switch # = SW-16 address * 16 + 8 + Bank B switch input #
    #
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #                  'NC' (normally closed.  Common for optos)?
    nudgeLeft:
        number: SD10 #Address:0 Bank:B Switch:2
        tags: ballsearchStop,totalAnnihilationIgnored
    nudgeRight:
        number: SD12 #Address:0 Bank:B Switch:0
        tags: ballsearchStop,totalAnnihilationIgnored
    exit:
        number: SD7
    down:
        number: SD6
    up:
        number: SD5
    enter:
        number: SD4
PRCoils:
    #############################################################################
    # Coil numbering format: Ax-By-z:
    # Capital letters are required, lower case letters represent the numbers:
    # x : Board address (0-7)
    # y : Bank address (0 for A, 1 for B)
    # z : Output number (0-7)
    #############################################################################
    ###############################
    # Lucky 7 PD-16 Addresses
    # PD-16 #1 - Address 3
    ###############################
    nudgeLeft:
        number: A3-B1-3
        pulseTime: 30
        label:  'Nudge Coil Left'
    nudgeRight:
        number: A3-B1-2
        pulseTime: 30
        label: 'Nudge Coil Right'
PRLamps:
    removeMe:
        number: L11
PRLEDs:
    #################################################################
    # LED numbering format: Ax-Rr-Gg-Bb
    # x = PD-LED board address
    # r = LED output number connected to the red input of an LED
    # g = LED output number connected to the green input of an LED
    # b = LED output number connected to the blue input of an LED
    #################################################################

    #################################################################
    # Lucky 7 PD-LED Addresses
    # PD-LED #1 (Upper) - Address 4
    # PD-LED #1 (Upper) - Address 5
    #################################################################

    #################################################################
    # SCORE DISPLAYS
    # Player 1 - Display 1
    #################################################################
    Player1_1A:
        number: A4-R0
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 1A'
    Player1_1B:
        number: A4-R1
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 1B'
    Player1_1C:
        number: A4-R2
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 1C'
    Player1_1D:
        number: A4-R3
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 1D'
    Player1_1E:
        number: A4-R4
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 1E'
    Player1_1F:
        number: A4-R5
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 1F'
    Player1_1G:
        number: A4-R6
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 1G'
    Player1_1DP:
        number: A4-R7
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 1DP'
    #################################################################
    # Player 1 - Display 2
    #################################################################
    Player1_2A:
        number: A4-R8
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 2A'
    Player1_2B:
        number: A4-R9
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 2B'
    Player1_2C:
        number: A4-R10
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 2C'
    Player1_2D:
        number: A4-R11
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 2D'
    Player1_2E:
        number: A4-R24
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 2E'
    Player1_2F:
        number: A4-R25
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 2F'
    Player1_2G:
        number: A4-R26
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 2G'
    Player1_2DP:
        number: A4-R27
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 2DP'
    #################################################################
    # Player 1 - Display 3
    #################################################################
    Player1_3A:
        number: A4-R29
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 3A'
    Player1_3B:
        number: A4-R29
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 3B'
    Player1_3C:
        number: A4-R30
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 3C'
    Player1_3D:
        number: A4-R31
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 3D'
    Player1_3E:
        number: A4-R32
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 3E'
    Player1_3F:
        number: A4-R33
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 3F'
    Player1_3G:
        number: A4-R34
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 3G'
    Player1_3DP:
        number: A4-R35
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player1 3DP'
    #################################################################
    # SCORE DISPLAYS
    # Player 2 - Display 1
    #################################################################
    Player2_1A:
        number: A4-R48
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 1A'
    Player2_1B:
        number: A4-R49
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 1B'
    Player2_1C:
        number: A4-R50
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 1C'
    Player2_1D:
        number: A4-R51
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 1D'
    Player2_1E:
        number: A4-R52
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 1E'
    Player2_1F:
        number: A4-R53
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 1F'
    Player2_1G:
        number: A4-R54
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 1G'
    Player2_1DP:
        number: A4-R55
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 1DP'
    #################################################################
    # Player 2 - Display 2
    #################################################################
    Player2_2A:
        number: A4-R56
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 2A'
    Player2_2B:
        number: A4-R57
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 2B'
    Player2_2C:
        number: A4-R58
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 2C'
    Player2_2D:
        number: A4-R59
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 2D'
    Player2_2E:
        number: A4-R72
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 2E'
    Player2_2F:
        number: A4-R73
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 2F'
    Player2_2G:
        number: A4-R74
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 2G'
    Player2_2DP:
        number: A4-R75
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 2DP'
    #################################################################
    # Player 1 - Display 3
    #################################################################
    Player2_3A:
        number: A4-R76
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 3A'
    Player2_3B:
        number: A4-R77
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 3B'
    Player2_3C:
        number: A4-R78
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 3C'
    Player2_3D:
        number: A4-R79
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 3D'
    Player2_3E:
        number: A4-R80
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 3E'
    Player2_3F:
        number: A4-R81
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 3F'
    Player2_3G:
        number: A4-R82
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 3G'
    Player2_3DP:
        number: A4-R83
        polarity: False
        tags: Player1ScoreDisplay
        label: 'Player2 3DP'




watchdog_time: 2000
